export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOADING_USER = 'LOADING_USER';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';
export const LOADING_CREDIT_CARDS = 'LOADING_CREDIT_CARDS';
export const CREDIT_CARDS_LOADED = 'GET_CREDIT_CARDS';
export const ADD_CREDIT_CARD = 'ADD_CREDIT_CARD';
export const DELETING_CARD = 'DELETING_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

export const LOADING_RESERVATIONS = 'LOADING_RESERVATIONS';
export const RESERVATIONS_LOADED_SUCCESS = 'RESERVATIONS_LOADED_SUCCESS';
export const RESERVATIONS_LOADED_FAILURE = 'RESERVATIONS_LOADED_FAILURE';

export const REFRESHING_RESERVATIONS = 'REFRESHING_RESERVATIONS';
export const RESERVATIONS_REFRESHED_SUCCESS =
  '  RESERVATIONS_REFRESHED_SUCCESS';
export const RESERVATIONS_REFRESHED_FAILURE =
  '  RESERVATIONS_REFRESHED_FAILURE';

export const LOADING_MORE_HISTORY_RESERVATIONS =
  'LOADING_MORE_HISTORY_RESERVATIONS';
export const MORE_HISTORY_RESERVATIONS_LOADED_SUCCESS =
  'MORE_HISTORY_RESERVATIONS_LOADED_SUCCESS';
export const MORE_HISTORY_RESERVATIONS_LOADED_FAILURE =
  'MORE_HISTORY_RESERVATIONS_LOADED_FAILURE';

export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_FAILURE = 'CANCEL_RESERVATION_FAILURE';

export const START_ANIMATION = 'START_ANIMATION';
export const FINISH_ANIMATION = 'FINISH_ANIMATION';
