export const LOADING_USER = 'LOADING_USER';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILURE = 'USER_LOADED_FAILURE';

export const UPDATING_USER = 'UPDATING_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAILURE = 'UPDATE_USER_ADDRESS_FAILURE';

export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILURE = 'UPDATE_USER_PASSWORD_FAILURE';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOADING_CREDIT_CARDS = 'LOADING_CREDIT_CARDS';
export const CREDIT_CARDS_LOADED = 'GET_CREDIT_CARDS';
export const ADD_CREDIT_CARD = 'ADD_CREDIT_CARD';
export const DELETING_CARD = 'DELETING_CARD';
export const DELETE_CARD = 'DELETE_CARD';

export const LOADING_USER_ADDRESS = 'LOADING_USER_ADDRESS';
export const USER_ADDRESS_LOADED_SUCCESS = 'USER_ADDRESS_LOADED_SUCCESS';
export const USER_ADDRESS_LOADED_FAILURE = 'USER_ADDRESS_LOADED_FAILURE';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const LOADING_USER_CONFIGURATION = 'LOADING_USER_CONFIGURATION';
export const USER_CONFIGURATION_LOADED_SUCCESS =
  'USER_CONFIGURATION_LOADED_SUCCESS';
export const USER_CONFIGURATION_LOADED_FAILURE =
  'USER_CONFIGURATION_LOADED_FAILURE';

export const LOADING_RESERVATIONS = 'LOADING_RESERVATIONS';
export const RESERVATIONS_LOADED_SUCCESS = 'RESERVATIONS_LOADED_SUCCESS';
export const RESERVATIONS_LOADED_FAILURE = 'RESERVATIONS_LOADED_FAILURE';

export const REFRESHING_RESERVATIONS = 'REFRESHING_RESERVATIONS';
export const RESERVATIONS_REFRESHED_SUCCESS =
  '  RESERVATIONS_REFRESHED_SUCCESS';
export const RESERVATIONS_REFRESHED_FAILURE =
  '  RESERVATIONS_REFRESHED_FAILURE';

export const LOADING_MORE_HISTORY_RESERVATIONS =
  'LOADING_MORE_HISTORY_RESERVATIONS';
export const MORE_HISTORY_RESERVATIONS_LOADED_SUCCESS =
  'MORE_HISTORY_RESERVATIONS_LOADED_SUCCESS';
export const MORE_HISTORY_RESERVATIONS_LOADED_FAILURE =
  'MORE_HISTORY_RESERVATIONS_LOADED_FAILURE';

export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_FAILURE = 'CANCEL_RESERVATION_FAILURE';

export const START_ANIMATION = 'START_ANIMATION';
export const FINISH_ANIMATION = 'FINISH_ANIMATION';
