export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOADING_USER = 'LOADING_USER';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';
export const LOADING_CREDIT_CARDS = 'LOADING_CREDIT_CARDS';
export const CREDIT_CARDS_LOADED = 'GET_CREDIT_CARDS';
export const ADD_CREDIT_CARD = 'ADD_CREDIT_CARD';
export const DELETING_CARD = 'DELETING_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const LOADING_RESERVATIONS = 'LOADING_RESERVATIONS';
export const RESERVATIONS_LOADED = 'RESERVATIONS_LOADED';
export const MORE_HISTORY_RESERVATIONS_LOADED =
  'MORE_HISTORY_RESERVATIONS_LOADED';
export const LOADING_MORE_HISTORY_RESERVATIONS =
  'LOADING_MORE_HISTORY_RESERVATIONS';
